### ISSUE TITLE
Add running instructions in README

### ISSUE THREAD

**Issue by madan96** [dyelax/encore.ai#2]
Can you please add the instructions on how to run the scripts and train the network for different singers.

**Comment by dyelax** [comment]
Thanks for your interest – will do this weekend!

**Comment by loretoparisi** [comment]
@dyelax very nice project! 💯 
I did something very similar using the good [char-rnn](https://github.com/karpathy/char-rnn), so
I have started playing with it a little bit:

```
cd data_wrangling
mkdir data
```

then we create the requested `a-z` file index

```
$ python
Python 2.7.10 (default, Oct 23 2015, 19:19:21) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> a_z = list(map(chr, range(97, 123)))
>>> a_z
['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']
>>> for letter in a_z:
...     open('data/'+letter+'.txt', 'a').close()
... 
>>> 
```

then scrape the artists

```
$ python get_all_artists.py 
```

and combine them in `unified_artists.txt`

```
$ python combine_artists.py 
```

then we need to hand pick some artists

```
$ cat >> hand_picked.txt
m/myartist.html
^C
```

and we need `artist_data` and `artists` folders then

```
$ mkdir artist_data
$ mkdir artists
```

so that we can get all songs

```
$ python get_all_songs.py 
```

NOTE. I just moved to `completed_artists.txt` the contents of `unified_artists.txt`, I assume the need for this file is to have a sublist of artists from the last one.

and then all lyrics for that artist

```
$ python get_song_lyrics.py myartist
```

so you should have like

```
├── artist_data
│   ├── myartist.txt
│   └── welcome_to_az.txt
├── artists
│   └── myartist
├── combine_artists.py
├── completed_artists.txt
├── data
│   ├── a.txt
│   ├── b.txt
│   ├── c.txt
│   ├── d.txt
│   ├── e.txt
│   ├── f.txt
│   ├── g.txt
│   ├── h.txt
│   ├── i.txt
│   ├── j.txt
│   ├── k.txt
│   ├── l.txt
│   ├── m.txt
│   ├── n.txt
│   ├── o.txt
│   ├── p.txt
│   ├── q.txt
│   ├── r.txt
│   ├── s.txt
│   ├── t.txt
│   ├── u.txt
│   ├── v.txt
│   ├── w.txt
│   ├── x.txt
│   ├── y.txt
│   └── z.txt
├── get_all_artists.py
├── get_all_songs.py
├── get_song_lyrics.py
├── hand_picked.txt
├── quick_clean.py
├── unified_artists.txt
└── word_count.py
```

where `myartist/` subfolder will have the song lyrics.

We can quickly count words for that artist

```
$ python word_count.py myartist
9319
```

The script `quick_clean.py` must be fixed since an artist name is hardcoded there ;)

I then suggest to install `tensorflow` in a `virtualenv` nutshell ( I assume we are on `MacOS` here)

```
$ virtualenv --system-site-packages ~/tensorflow
$ source ~/tensorflow/bin/activate
$ export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-0.10.0rc0-py2-none-any.whl
$ sudo pip install --upgrade $TF_BINARY_URL
$ python -c 'import os; import inspect; import tensorflow; print(os.path.dirname(inspect.getfile(tensorflow)))'
```

ok.
NOTE. The `data/`, `artists`, `artists_data` folders must be in the root folders since they are referenced by the source in `code/` with a `../`.

Let's start the training now (I assume we are not using GPU here)

```
$ python runner.py myartist
Process data...
1625
Init model...
WARNING:tensorflow:<tensorflow.python.ops.rnn_cell.BasicLSTMCell object at 0x1170b5990>: Using a concatenated state is slower and will soon be deprecated.  Use state_is_tuple=True.
Init variables...
Training model...
Step: 1 | loss: 7.946285
...
```

Wit a bit of luck it should get the work done at some point...

_NOTE. We assume that the developer is going to respect the terms & conditions of the lyrics provider here._

**Comment by dyelax** [comment]
Added to README in latest commit!

**Comment by loretoparisi** [comment]
@dyelax In my case I had something like 30 songs from an artist. I started the training and I reached out about 250K steps and it was still running.

I have read in the updated README `Our models were all trained for 30,000 steps.`, so when it should stop?

If something happens during processing, there are checkpoints like `char-rnn` does? It happened to me to have data in the `save/` folder, the process terminated for some reason, and at the second launch it started from beginning.

**Comment by dyelax** [comment]
We manually stopped training after 30,000 steps. The current program will run indefinitely until you stop it. Model checkpoints are saved every 5,000 steps.

You are definitely going to need more than 30 songs to successfully train a model. With so little data it will overfit and start just producing full songs from the train data. We recommend having over 100,000 words.

Please check the usage instructions for info on how to load a partially-trained model. (use the `-l` flag with a path to a saved `.ckpt` file.)

**Comment by loretoparisi** [comment]
@dyelax yes thank you. I will check the `-l` option then, since I'm running through a `docker` tensorflow machine on AWS with GPU, performances seems to be very good in this first test, so I'm going to scale to more songs. At average, in your estimations you have like 100K words/30K steps by artist then? that's an interesting benchmark!

**Comment by loretoparisi** [comment]
@dyelax I have a clue about the `dataset` size that you described, supposed that we are talking about a single artist and its production (i.e. released albums).
If you take a look here http://lab.musixmatch.com/largest_vocabulary/
we did a analysis of the music vocabulary by

• VOCABULARY SIZE The number of unique words (across any language) used by a musician in 100 (or less) densest songs across their career. 

• LYRICAL DENSITY The total number of words (across any language) used by a musician in 100 (or less) densest songs across their career. 

• NEW WORD INTERVAL (N.W.I) On average, the number of words after which a new word is used by the musician. This is the ratio of (Lyrical density / Vocabulary Size). An N.W.I of X means every Xth word in the lyrics of the artist is a new word, that is, a word he/she has never used before in any of his earlier songs. 

So, assumed this, could we restrict the interval to less than 100k words/artist in your experiments?

**Comment by dyelax** [comment]
@loretoparisi – Thanks for the link, I'll check that out! I don't understand your question though. The reason we advise having at least 100k words in your training data is that with fewer total words, the network tends to overfit and just reproduce songs from the training data. You can train on fewer than that. For example, our Taylor Swift model only had about 40k words, but you can tell that most of the generated lines are pulled directly from the training data.

**Comment by loretoparisi** [comment]
@dyelax thanks for the clarification. The input must be a lyrics (i.e. a structured test as a lyrics) or can be ngrams of the lyrics document?
Thank you again.

**Comment by dyelax** [comment]
@loretoparisi What do your files look like? We just used .txt files with the lyric text.

**Comment by loretoparisi** [comment]
@dyelax I was wondering what happens using bag of words of ngrams of a chosen N size (like 3 or 5). I guess the model would be completely different in that case.

**Comment by dyelax** [comment]
Yeah, you would have to change our data processing code. What we wrote specifically works for full songs

**Comment by loretoparisi** [comment]
@dyelax ok thanks it make sense for this kind of network. Good I will share you some results as soon as I run it.
